build: minlexbfs disjcnt revedges rtd

minlexbfs: minlexbfs.cpp
	g++ minlexbfs.cpp -o minlexbfs -g

disjcnt: disjcnt.cpp
	g++ disjcnt.cpp -o disjcnt -g -std=c++11

rtd: rtd.cpp
	g++ rtd.cpp -o rtd -g -std=c++11

revedges: revedges.cpp
	g++ revedges.cpp -o revedges -g -std=c++11

run-p1:
	./minlexbfs

run-p2:
	./disjcnt

run-p3:
	./rtd

run-p4:
	./revedges

clean:
	rm -rf minlexbfs disjcnt rtd revedges
