#define ERR1 "IBANK> -1 : Clientul nu este autentificat"
#define ERR2 "IBANK> -2 : Sesiune deja deschisa"
#define ERR3 "IBANK> -3 : Pin gresit"
#define ERR4 "IBANK> -4 : Numar card inexistent"
#define ERR5 "IBANK> -5 : Card blocat"
#define ERR6 "IBANK> -6 : Operatie esuata"
#define ERR7 "UNLOCK> -7 : Deblocare esuata"
#define ERR8 "IBANK> -8 : Fonduri insuficiente"
#define ERR9 "IBANK> -9 : Operatie anulata"

#define DISCONNECTED "IBANK> Clientul a fost deconectat"
#define TRANSFER "IBANK> Transfer realizat cu succes"
#define SECRET_PSSWD "UNLOCK> Introdu parola secreta"
#define UNLOCKED "UNLOCK> Card deblocat"
