build: frati planificare numaratoare ursi

ursi: ursi.cpp
	g++ ursi.cpp -o ursi -g

numaratoare: numaratoare.cpp
	g++ numaratoare.cpp -o numaratoare -g

frati: frati.cpp
	g++ frati.cpp -o frati -g

planificare: planificare.cpp
	g++ planificare.cpp -o planificare -g

run-p1: frati
	./frati

run-p2: ursi
	./ursi

run-p3: planificare
	./planificare

run-p4: numaratoare
	./numaratoare

clean: frati planificare numaratoare ursi
	rm frati planificare numaratoare ursi
